### PR TITLE
Stop ticker from scrolling when hovered

### PR DESCRIPTION
**Pull request by mygreymatter**
Hi,
I implemented a feature such that the ticker stops scrolling when a user hovers at it.
I guess I made it simple and effective.

Please revert back if anything is not right.

### CODE REVIEW

**Comment by ttbarnes** [comment]
Thanks! Looks good, but could you please update the tests?

**Comment by mygreymatter** [comment]
I do not have knowledge to write tests in Javascript.

**Comment by ttbarnes** [comment]
OK, if you could change the PR to merge into the `dev` branch instead of master, we can merge and i'll add some tests.

**Comment by ttbarnes** [comment]
I've added some tests here if you wanted to see @mygreymatter c9be7ab and 47069a9

**Pull request closed without merging**
